### ISSUE TITLE
update readme to include apt install option

### ISSUE THREAD

**Issue by joespeed** [ros2/rmw_cyclonedds#105]
please update readme to 1st show "How to" with apt install before showing how to build it

How to use 
1) Install:
`apt install ros-eloquent-rmw-cyclonedds-cpp`
`            (or dashing)`
2) Set env variable and run as usual
`RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
`
3) Confirm RMW: In Eloquent, to confirm which RMW you're using
`ros2 doctor --report`

**Comment by eboasson** [comment]
I don’t think that makes sense: if people go to github to get it they’ll more than likely want to build it themselves. ROS2 has clear instructions on how to install additional middleware as well.

**Comment by rotu** [comment]
Fixed in #131
