### ISSUE TITLE
crashes on Windows Debug

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rmw_cyclonedds#120]
See https://ci.ros2.org/job/ci_windows-metal/5/ for a build with only CycloneDDS testing `test_communication`. When invoking `test_publisher_cpp.exe Empty /topic` it exits with an assertion:

> vector subscription out of range

Overall it fails 88 tests. I assume they are all related to the same reason.

**Comment by dirk-thomas** [comment]
The bug is related to this call: https://github.com/ros2/rmw_cyclonedds/blob/025762ac4f21c7d77b1e3cb09642debc7bb14193/rmw_cyclonedds_cpp/src/Serialization.cpp#L513-L514

The invocation of `sequence_contents()` tries to get the pointer to the data of a vector with size 0. Accessing `[0]` from that vector results in an out of bound exception. Since the `count` argument is zero this shouldn't try to access the vector data.

**Comment by dirk-thomas** [comment]
@rotu FYI since you seem to have touched this part of the code recently.

**Comment by rotu** [comment]
Thanks, @dirk-thomas! On it!

**Comment by eboasson** [comment]
@dirk-thomas Hah, I had *just* managed to catch this crash in the debugger! It took me forever because Windows how much I hate it and does everything in its power to thwart my efforts.

@rotu Thanks!
