### ISSUE TITLE
Events still need to be implemented

### ISSUE THREAD

**Issue by eboasson** [ros2/rmw_cyclonedds#13]
## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by rotu** [comment]
@eboasson Can this be deleted or updated with details?

**Comment by eboasson** [comment]
Thanks @rotu for going over the old stuff and making sure it gets closed or updated. This is all fully supported now..
