### ISSUE TITLE
Fix serialization on non-32-bit, big-endian systems - dashing-eloquent

### ISSUE THREAD

**Issue by dodsonmg** [ros2/rmw_cyclonedds#188]
## Bug report

**Required Info:**

- Operating System:
Ubuntu 18.04

- Installation type:
Source installation

- Version or commit hash:
`dashing-eloquent` branch provided with ROS2 dashing

- DDS implementation:
rmw_implementation = cyclonedds

- Client library (if applicable):
N/A

#### Steps to reproduce issue
This is an issue with serialisation on big-endian systems and is discussed here:

[eclipse-cyclonedds/cyclonedds#488 ](https://github.com/eclipse-cyclonedds/cyclonedds/issues/488)

The fix for this has already been merged with `master` (#159), and I was hoping it could be pulled into `dashing-eloquent`.

I think the patch used for #159 on `master` can be merged directly into `dashing-eloquent`.  I'm happy to submit the PR myself.

**Comment by eboasson** [comment]
I'm in favour. Please do submit a PR!

**Comment by dodsonmg** [comment]
Thanks!  PR submitted.  #189.
