### ISSUE TITLE
cyclonedds tests related to OpenSSL are failing on Windows

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rmw_cyclonedds#201]
The test failures started 20 days ago.

Note the current Windows jobs use OpenSSL 1.1.1g.

Test failure example: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1591/testReport/projectroot.src.security.builtin_plugins/tests/CUnit_ddssec_builtin_validate_local_identity_no_file/

**Comment by eboasson** [comment]
Unfortunately it got merged too late for last night's run of builds.

**Comment by dirk-thomas** [comment]
Thanks for the quick fix.

> 

No worry, there is always a next build coming :wink:
