### ISSUE TITLE
failing test checking node names

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rmw_cyclonedds#211]
This nightly test is failing for CycloneDDS: http://build.ros2.org/view/Rci/job/Rci__nightly-cyclonedds_ubuntu_focal_amd64/29/testReport/rclcpp_lifecycle/TestDefaultStateMachine/test_graph/

Each test in the gtest creates a node with the name `/testnode`. But when it goes out of scope (which results in calling `rmw_destroy_node`) the metadata about the node isn't being removed. As a result the specific failing test reports 23 nodes (all with the same node).

The function never calls `common->graph_cache.remove_node()`. On the contrary - it even adds the node another time during the destruction: https://github.com/ros2/rmw_cyclonedds/blob/4383911781047513545bc61092150d3ca080fdab/rmw_cyclonedds_cpp/src/rmw_node.cpp#L1335

Inserting two calls below the `rmw_publish()` call within `rmw_destroy_node()` makes the test pass but I am not sure if that is the right way to address the problem.

<details>

<summary>Potential patch:</summary>

```
iff --git a/rmw_cyclonedds_cpp/src/rmw_node.cpp b/rmw_cyclonedds_cpp/src/rmw_node.cpp
index 53ca3c4..279ac57 100644
--- a/rmw_cyclonedds_cpp/src/rmw_node.cpp
+++ b/rmw_cyclonedds_cpp/src/rmw_node.cpp
@@ -1335,6 +1335,8 @@ extern "C" rmw_ret_t rmw_destroy_node(rmw_node_t * node)
       common->graph_cache.add_node(common->gid, node->name, node->namespace_);
     result_ret = rmw_publish(
       common->pub, static_cast<void *>(&participant_msg), nullptr);
+    static_cast<void>(common->graph_cache.remove_node(common->gid, node->name, node->namespace_));
+    static_cast<void>(common->graph_cache.remove_node(common->gid, node->name, node->namespace_));
   }
 
   rmw_context_t * context = node->context;
```

</details>

**Comment by eboasson** [comment]
@dirk-thomas there's an even simpler fix: the `add_node` was a copy-paste error and it should've been a call to `remove_node` instead. That at least makes sense, it fixes the test and brings it in line with the `rmw_fastrtps`.
