### ISSUE TITLE
New cyclonedds release for rolling

### ISSUE THREAD

**Issue by ivanpauno** [ros2/rmw_cyclonedds#316]
After https://github.com/ros2/rmw_cyclonedds/pull/309, the rolling PR checker is failing, e.g.: https://build.ros2.org/job/Rpr__rmw_cyclonedds__ubuntu_focal_amd64/239/console#console-section-6.

We will need a new `cyclonedds` realease that includes the `dds_data_allocator_init_heap()`.

**Comment by ivanpauno** [comment]
@eboasson is it possible to do a new release?

**Comment by eboasson** [comment]
Absolutely, I’ll do it when I’m home again. (I went for a bike ride and saw your note when I stopped to take a picture 🙂.)

**Comment by eboasson** [comment]
@ivanpauno I just created `0.8.0beta6`.

**Comment by ivanpauno** [comment]
Thanks @eboasson !!!
I will do a `bloom-release` with the new tag so it gets updated in `rosdistro`.

> I went for a bike ride and saw your note when I stopped to take a picture

Sorry to disturb the ride, hope you have enjoyed it!!

**Comment by ivanpauno** [comment]
I have opened the rosdistro PR: https://github.com/ros/rosdistro/pull/29767
