### ISSUE TITLE
Shared memory transport without fixing the size of messages

### ISSUE THREAD

**Issue by Yadunund** [ros2/rmw_cyclonedds#341]
## Feature request
My understanding is that shared memory transport is achieved in `cyclonedds v0.8` via `iceoryx`. But one of the requirements is to have messages of fixed sizes. I agree that this would be required for true zero-copy (in conjunction with using the `borrow_loaned_message()` API), but it shouldn't be the case for shared memory transport? I'm not too familiar with `iceorxy` but is there a way to configure an upper bound for the size of the shared memory segment that each process has access to? Or any other way to enable shared memory transport without fixing the size of messages?

**Comment by Yadunund** [comment]
Hi @MatthiasKillat,
Thanks a lot for the quick response. It is great to hear that support for non-fixed sizes messages is a work in progress. Are you able to comment on any rough timeline for when this feature would be available?

> The next step will be to support zero-copy for dynamic types (think std::vector).
This sounds totally amazing! Is there a design document on how this will be achieved?

**Comment by clalancette** [comment]
Since this is mostly a question, I'm going to go ahead and close this issue out.  If I'm wrong about that, please feel free to reopen this issue.
