### ISSUE TITLE
slow publishing and performance for custom messages with large arrays

### ISSUE THREAD

**Issue by berndpfrommer** [ros2/rmw_cyclonedds#346]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - ROS2 galactic standard ubuntu package installed via apt
- Version or commit hash:
 This is what the apt package info says:  `` ros-galactic-cyclonedds/focal,now 0.8.0-5focal.20210608.002038 amd64 [installed,automatic]``
- DDS implementation:
  - cyclonedds
- Client library (if applicable):
  - rclcpp
- Hardware:
  AMD Ryzen 7 4800H with 64GB of memory

#### Steps to reproduce issue
I have made a very small repo with the below demo code and instructions how to run:
https://github.com/berndpfrommer/ros2_issues
Here is the source code for the publisher:
```
#include <unistd.h>

#include <rclcpp/rclcpp.hpp>
#include <ros2_issues/msg/test_array_complex.hpp>
#include <thread>

template <class MsgType>
struct TestPublisher : public rclcpp::Node
{
  explicit TestPublisher(const rclcpp::NodeOptions & options)
  : Node("test_publisher", options)
  {
    pub_ = create_publisher<MsgType>(
      "~/array", declare_parameter<int>("q_size", 1000));
    thread_ = std::thread([this]() {
      rclcpp::Rate rate(declare_parameter<int>("rate", 1000));
      const int numElements = declare_parameter<int>("num_elements", 100);
      rclcpp::Time t_start = now();
      size_t msg_cnt(0);
      const rclcpp::Duration logInterval = rclcpp::Duration::from_seconds(1.0);
      while (rclcpp::ok()) {
        MsgType msg;
        msg.header.stamp = now();
        msg.elements.resize(numElements);
        pub_->publish(msg);
        rate.sleep();
        msg_cnt++;
        rclcpp::Time t = now();
        const rclcpp::Duration dt = t - t_start;
        if (dt > logInterval) {
          RCLCPP_INFO(get_logger(), "pub rate: %8.2f", msg_cnt / dt.seconds());
          t_start = t;
          msg_cnt = 0;
        }
      }
    });
  }
  // -- variables                                                                                                                                                                                                  
  typename rclcpp::Publisher<MsgType>::SharedPtr pub_;
  std::thread thread_;
};

int main(int argc, char * argv[])
{
  rclcpp::init(argc, argv);
  auto node =
    std::make_shared<TestPublisher<ros2_issues::msg::TestArrayComplex>>(
      rclcpp::NodeOptions());
  rclcpp::spin(node);
  rclcpp::shutdown();
  return 0;
}
```
It uses the following custom message for ``TestArrayComplex``:
```
std_msgs/Header header
# test array of elements
TestElement[] elements
```
and the TestElement of the array is defined as:
```
uint16 x
uint16 y
builtin_interfaces/Time ts
bool polarity
```

#### Expected behavior
Under ROS1 I can publish 1000 msgs/sec  with  100,000 elements per message *and* receive at a rate of 1000Hz with ``rostopic hz``

#### Actual behavior
Under ROS2 (galactic), already the publishing fails to keep up at a message size of 5,000 elements. Running the publisher with 
```
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ros2 run ros2_issues publisher_node --ros-args -p num_elements:=5000 -p rate:=1000
```
produces this output:
```
634242922.738549 [0] publisher_: using network interface wlo1 (udp/192.168.1.234) selected arbitrarily from: wlo1, virbr0, virbr1, docker0
[INFO] [1634242923.747148904] [test_publisher]: pub rate:   369.34
[INFO] [1634242924.749220049] [test_publisher]: pub rate:   373.22
...
```
So not even the publishing is full speed, without any subscriber to the topic. I see the publisher running at 100 %CPU, so something is really heavy weight about publishing.
Worse, running ``rostopic hz`` shows a rate of about 30 msg/s.
```
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ros2 topic hz -w 100 /test_publisher/array
1634243031.116776 [0]       ros2: using network interface wlo1 (udp/192.168.1.234) selected arbitrarily from: wlo1, virbr0, virbr1, docker0
average rate: 31.275
        min: 0.030s max: 0.041s std dev: 0.00314s window: 33
average rate: 30.502
        min: 0.030s max: 0.044s std dev: 0.00351s window: 63
```
This  is what I get from rostopic bw. The size of the message (about 80kb) agrees with what I computed by hand:
```
5.20 MB/s from 100 messages
        Message size mean: 0.08 MB min: 0.08 MB max: 0.08 MB
```

I tried ``sudo` sysctl -w net.core.rmem_max=8388608 net.core.rmem_default=8388608`` and also was able to restrict the interface to loopback (lo) but no improvement.

FastRTPS is a bit better, at least here I can send messages with up to 50,000 elements before it falls off at 110,000 messages:
```
RMW_IMPLEMENTATION=rmw_fastrtps_cpp ros2 run ros2_issues publisher_node_complex --ros-args -p num_elements:=110000 -p rate:=1000                                       
[INFO] [1634243372.579736663] [test_publisher]: pub rate:   404.43
[INFO] [1634243373.581322637] [test_publisher]: pub rate:   391.37
[INFO] [1634243374.583210605] [test_publisher]: pub rate:   414.22
```
But if I send messages of size 5,000, ``rostopic hz`` also shows about 30Hz, similar to rmw_cyclonedds_cpp.

#### Additional information

This is a show stopper for porting e.g. a driver for an event based camera from ROS1 to ROS2, see here: https://github.com/berndpfrommer/metavision_ros_driver.

The hardware is a 8-core AMD Ryzen laptop, less than 1 year old, so definitely not a slow machine, and this is all running on-machine, no network traffic.

To run the above code it is fastest to clone the [very small repo](https://github.com/berndpfrommer/ros2_issues) linked above.

**Comment by eboasson** [comment]
Given that there's a lot of info on discourse and that the immediate problem has been addressed, I'll close this issue. Don't hesitate to open new ones (or even revive this one if that's appropriate) if you have more questions or — unfortunately — run into problems again.

**Comment by berndpfrommer** [comment]
Other users on discourse have requested that I create an open issue on this such that the performance issues are addressed or at least documented that way:
https://discourse.ros.org/t/ros2-speed/20162/30?u=bernd_pfrommer
Would you mind simply re-opening this issue? Would save me the work of creating an almost identical issue.
Also somebody asked to try iceoryx:
https://discourse.ros.org/t/ros2-speed/20162/31?u=bernd_pfrommer
Would iceoryx make much difference, given that the bottleneck seems to be serializing/deserializing?

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros2-speed/20162/32

**Comment by christophebedard** [comment]
Instead of keeping an issue open for documentation, we should find somewhere under the ROS 2 docs to put a summary of this: https://github.com/ros2/ros2_documentation. It looks like there's already a page for this: https://docs.ros.org/en/rolling/How-To-Guides/DDS-tuning.html

**Comment by berndpfrommer** [comment]
@christophebedard from what I understand this is not really DDS tuning. It would be a new section: how to work around slow ROS2 serialization? At this point I'm not even sure it's a ROS2 issue or just serialization slowness for all RMW's that I've tested (fastrtps and cyclonedds).
And I agree that for documentation a new issue should be created or better, a PR with improved docs should be submitted. But my preference would be to have the issue fixed rather than document further so for that alone an issue should be kept open. Or is the serialization performance drop between ROS1 and ROS2 unfixable?

**Comment by berndpfrommer** [comment]
Never mind, I squeezed it under the DDS tuning section for now:
https://github.com/ros2/ros2_documentation/pull/2096

**Comment by christophebedard** [comment]
> It would be a new section: how to work around slow ROS2 serialization? At this point I'm not even sure it's a ROS2 issue or just serialization slowness for all RMW's that I've tested (fastrtps and cyclonedds).

Sorry, my point was mostly about documenting some of the practical tuning tips/workarounds that were mentioned here and over on Discourse. However, I see that most of it is actually already documented for Cyclone DDS on the page I linked to.

> But my preference would be to have the issue fixed rather than document further so for that alone an issue should be kept open. Or is the serialization performance drop between ROS1 and ROS2 unfixable?

I can't comment on whether it can be fixed or not. I assume it can at least be improved, but not right away, so documenting it alongside the other DDS tuning/tips is a first step (which you have done, thank you).

Perhaps this issue should be re-named to specifically mention "high (de)serialization cost of custom messages with large variable-sized arrays of non-primitive types" and re-opened. Then the ROS 2 docs can link to it. I'll let the actual maintainers consider it.

**Comment by christophebedard** [comment]
> Perhaps this issue should be re-named to specifically mention "high (de)serialization cost of custom messages with large variable-sized arrays of non-primitive types" and re-opened.

Although it's not a Cyclone-specific issue from what I understand.

**Comment by fake-name** [comment]
>  "high (de)serialization cost of custom messages with large variable-sized arrays of non-primitive types" 

It's also not specific to custom messages, it's true of *any* message with *any* non-primitive type over *any* DDS. 

There is something seriously, *seriously* wrong with how the serialization works for it to perform as badly as it does.

**Comment by eboasson** [comment]
Isn't it simply a case of an array of non-primitive types mapping onto a list of objects in Python, and so that you're running into the overhead of creating and deleting tons upon tons of objects?

I'm no Python expert and I really don't have the time or knowledge to try to improve the performance of the Python binding of ROS 2, but it is painful to see your disappointment. Thinking out loud: most data types tend to be numerical, maybe it'd be possible to map the data to numpy arrays? Would that be difficult?

**Comment by clalancette** [comment]
If we are talking about Python, serialization of large messages can still be slow, depending on the exact types of messages used.  You can see some of the bug reports at https://github.com/ros2/rclpy/issues/856 , https://github.com/ros2/rclpy/issues/836 , and https://github.com/ros2/rclpy/issues/630 .

The good news is that post-Foxy, we've improved the Python serialization for certain types.  But there are still types that are slow, and need someone to look at them.

> Thinking out loud: most data types tend to be numerical, maybe it'd be possible to map the data to numpy arrays? Would that be difficult?

So we actually do that for certain types already.  It's been a while since I looked at this, but I think that a) not all types are changed to numpy types, and b) even for the types that are, we are not always using the types in the most efficient way.

Anyway, if we *are* talking about Python, then the problem probably isn't CycloneDDS specific.  If your issue is similar to one of the ones I listed above, I suggest you watch those (or even better, contribute a pull request to fix it up).  If your issue is different, please feel free to open a new issue over on https://github.com/ros2/rclpy .

**Comment by fake-name** [comment]
My issues so far have been entirely in C++.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/high-cpu-load-for-simple-python-nodes/28324/18

**Comment by daisukes** [comment]
I had a similar issue here and found a solution for my environment.

- humble, navigation2, cyclone dds
- a large-size static map (3000 x 2000), global costmap always publishes the full map (1Hz)
- `rviz2` and `ros2 bag record` subscribe to the global costmap, velodyne_points and so on
- velodyne_packets is 10Hz, but velodyne_points is around 6Hz and delayed

I checked some documents/comments about tuning.

- mentions only rmem
  - https://docs.ros.org/en/rolling/How-To-Guides/DDS-tuning.html#cyclone-dds-tuning
  - https://github.com/ros2/rmw_cyclonedds#performance-recommendations
- mentions both rmem and wmem
  - https://discourse.ros.org/t/latency-and-throughput-in-ros2/4367/17

Only rmem settings did not work, but both rmem and wmem work like a charm!
In my case -16MB did not fix the issue, but 64MB works well.
```
sudo sysctl -w net.core.rmem_max=67108864 net.core.rmem_default=67108864
sudo sysctl -w net.core.wmem_max=67108864 net.core.wmem_default=67108864
```

**Comment by jimmyshe** [comment]
> I had a similar issue here and found a solution for my environment.
> 
>     * humble, navigation2, cyclone dds
> 
>     * a large-size static map (3000 x 2000), global costmap always publishes the full map (1Hz)
> 
>     * `rviz2` and `ros2 bag record` subscribe to the global costmap, velodyne_points and so on
> 
>     * velodyne_packets is 10Hz, but velodyne_points is around 6Hz and delayed
> 
> 
> I checked some documents/comments about tuning.
> 
>     * mentions only rmem
>       
>       * https://docs.ros.org/en/rolling/How-To-Guides/DDS-tuning.html#cyclone-dds-tuning
>       * https://github.com/ros2/rmw_cyclonedds#performance-recommendations
> 
>     * mentions both rmem and wmem
>       
>       * https://discourse.ros.org/t/latency-and-throughput-in-ros2/4367/17
> 
> 
> Only rmem settings did not work, but both rmem and wmem work like a charm! In my case -16MB did not fix the issue, but 64MB works well.
> 
> ```
> sudo sysctl -w net.core.rmem_max=67108864 net.core.rmem_default=67108864
> sudo sysctl -w net.core.wmem_max=67108864 net.core.wmem_default=67108864
> ```

This works.

**Comment by jimmyshe** [comment]
> sudo sysctl -w net.core.rmem_max=67108864 net.core.rmem_default=67108864
> sudo sysctl -w net.core.wmem_max=67108864 net.core.wmem_default=67108864

This is a working solution. 
I tested on Ubuntu 22.04 with humble and cyclone dds.

**Comment by berndpfrommer** [comment]
Sorry @daisukes and @jimmyshe I believe you are taking this issue off-topic. The original issue I opened arises with custom messages and is due to serialization and could *not* be fixed with some network memory settings as your comments indicate. The issues you are mentioning likely have a different underlying root cause.
