### ISSUE TITLE
Topic message loss under high load on loopback, no multicast

### ISSUE THREAD

**Issue by KenYN** [ros2/rmw_cyclonedds#350]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04 + Ubuntu 20.04/Docker
- Installation type:
  - Binaries
- Version or commit hash:
  - Galactic
- DDS implementation:
  - Cyclone DDS
- Client library (if applicable):
  -  rclcpp

#### Steps to reproduce issue
I have a very basic setup with four publishers sending a 1280x960xRGB8 `Image` message at 30 Hz to four subscribers in the same Composible Node and four in another, and `use_intra_process_comms = False`, then RViz running over RDP viewing the four images, and `ros2 bag record --all`. `sysctl -w net.core.rmem_max=64000000` is also set.

#### Expected behavior
The subscribers to report reception at 30Hz , and the bag file to contain frames received at 30 Hz

#### Actual behavior
With the machine load at about 90%, some subscribers report about 29.5% or less, and the bag file is also missing packets. Further investigation showed that some packets get sent by the publisher but fail to be received by the subscriber.

#### Additional information
Turning on `finer` logging on Cyclone, I cannot see any evidence of packet loss or retransmission, although I would think that would be a report-worthy event. I am using the default QoS settings, and a publish queue of 10, although I understand that doesn't get used, as well as a subscribe queue of 10.

**Comment by clalancette** [comment]
@KenYN Out of curiousity, what happens if you use Fast-RTPS instead?  Is the situation any different?

@eboasson Is there any light you can shine on what might be going on here?  I'm not entirely sure it is in rmw_cyclonedds/CycloneDDS issue, but it would be good to get your thoughts about this.

**Comment by eboasson** [comment]
The publish queue does get used, it controls what data is available for retransmit. A 64MB receive buffer should be more than enough to prevent packet loss (provided the receiver can at all keep up), but

>sysctl -w net.core.rmem_max=64000000

tells me only the maximum has been raised. The default is still small, which means Cyclone will then ask for a mere 1MB, and that is definitely small enough to make packet loss a possibility with a 4MB samples.

I'd try setting Cyclone's `Internal/MinimumSocketReceiveBufferSize` option to something large. 20MB should be large enough but 60MB should be ok, too.

**Comment by clalancette** [comment]
No response from the original reporter in several months, so I'll close this out.  Please feel free to keep commenting or reopen if you are still having a problem.
