### ISSUE TITLE
Unrecoverable error on rclpy raw subscriber when publisher closed

### ISSUE THREAD

**Issue by suurjaak** [ros2/rmw_cyclonedds#374]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - ros-foxy-rclpy 1.0.8-1focal.20220204.170855 (latest)
- DDS implementation:
  - ros-foxy-cyclonedds 0.7.0-1focal.20210901.023825 (latest)
  - ros-foxy-rmw-cyclonedds-cpp 0.7.8-1focal.20220204.165603 (latest)
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

```python3
import rclpy, std_msgs.msg

rclpy.init()
node = rclpy.create_node("node")
sub = node.create_subscription(std_msgs.msg.Bool, "/topic", print, 10, raw=True)
rclpy.spin(node)
```

```bash
ros2 topic pub /topic std_msgs/msg/Bool --once
```

#### Expected behavior

Subscriber prints received raw message.

#### Actual behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/__init__.py", line 191, in spin
    executor.spin_once()
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 714, in spin_once
    raise handler.exception()
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 422, in handler
    arg = take_from_wait_list(entity)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 347, in _take_subscription
    msg_info = _rclpy.rclpy_take(capsule, sub.msg_type, sub.raw)
_rclpy.RCLError: Failed to take_serialized from a subscription: error not set
```

Spinning stops, and restarting it has no more effect whatsoever

Same result if letting it publish N times and then stopping with Ctrl-C.

**Comment by eboasson** [comment]
I suspect a bug in the Foxy `rclpy`: it basically doesn't handle spurious "data available" events on the subscription properly. Those spurious events are triggered by the presence of a DDS message indicating an event on the subscription (for example, the disappearing of the writer) that doesn't have an analogue in the ROS 2 land, and so the RMW layer `take` says (OK, nothing taken), which the `rcl` layer translates to `take failed` which results in the Foxy `rclpy` raising this error.

It looks like `rclpy` got rewritten from Foxy to Galactic and that this got fixed at that point.

**Comment by suurjaak** [comment]
Should I open an issue in [rclpy](https://github.com/ros2/rclpy/) instead?

**Comment by eboasson** [comment]
I think so. Or you could see if you can switch to Galactic.

**Comment by suurjaak** [comment]
I see now there are a number of reports in rclpy on this already: https://github.com/ros2/rclpy/issues?q=is%3Aissue+cyclone.

I will take the discussion there. Thank you.
