### ISSUE TITLE
Gzserver crashes on ROS 2 Foxy w Cyclone DDS

### ISSUE THREAD

**Issue by QiangWuCN** [ros2/rmw_cyclonedds#395]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04 
- Installation type:
  - Binaries 
- Version or commit hash:
  - 0.7.3 
- DDS implementation:
  - Cyclone DDS 
- Client library (if applicable):
  - N/A 

#### Steps to reproduce issue

```
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp  gazebo -s libgazebo_ros_init.so /usr/share/gazebo-11/worlds/elevator.world

```

#### Expected behavior
Gazebo runs smoothly. Tested successfully w/ Fast DDS.

#### Actual behavior
Gzserver crashes within several minutes after starting with the following logging.

```
Warning [Model.cc:216] Non-unique name[door] detected 2 times in XML children of model with name[elevator].
Warning [Model.cc:309] Joint with name [door] in model with name [elevator] has a name collision, changing joint name to [door_joint].
1652881428.257805 []   gzserver: create_thread: gzserver: no free slot
```
#### Additional information
Ubuntu 20.04 + ROS 2 Foxy + Gazebo 11 is being used in a container, while the host OS is Ubuntu 20.04 and the Docker version is version 20.10.16.

Tried to enlarge the receive buffer size by using the below command, but didn't resolve the problem:

sudo sysctl -w net.core.rmem_max=8388608 net.core.rmem_default=8388608

**Comment by eboasson** [comment]
@QiangWuCN I suspect it is the same as https://github.com/eclipse-cyclonedds/cyclonedds/issues/479, so it would be worthwhile to try changing that if it is possible for you to do a custom build of `cyclonedds`.

**Comment by QiangWuCN** [comment]
@[eboasson](https://github.com/eboasson) Thanks a lot. The problem is fixed by building a custom build of cyclonedds. 

As for a 128 cores machine, the max number of threads is changed from "64" to "256"  (Tested "128" but still failed) in the source file:
[cyclonedds/src/core/ddsc/src/dds_init.c](https://github.com/eclipse-cyclonedds/cyclonedds/blob/b84eee5abbd4e935d3e47186e07ed93e4730b5f1/src/core/ddsc/src/dds_init.c#L113)
Line 113 in [b84eee5](https://github.com/eclipse-cyclonedds/cyclonedds/commit/b84eee5abbd4e935d3e47186e07ed93e4730b5f1)
```
 thread_states_init (64);
```

Just for the record, the following branches of cyclonedds and rmw_cyclonedds are used:
```
git clone https://github.com/eclipse-cyclonedds/cyclonedds eclipse-cyclonedds/cyclonedds -b release/0.7.x
git clone https://github.com/ros2/rmw_cyclonedds ros2/rmw_cyclonedds -b foxy
```
