### ISSUE TITLE
When using the ROS2 hub version for multi machine communication, B computer cannot view A computer topics when using Cyclonedds

### ISSUE THREAD

**Issue by LHZ-code** [ros2/rmw_cyclonedds#466]
Why can't computer B receive topic information from computer A when both computers use cyclonedds

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
