### ISSUE TITLE
Get unknown element for tags "Interfaces" and "SocketReceiveBufferSize" in config file for cyclonedds

### ISSUE THREAD

**Issue by stevenbrills** [ros2/rmw_cyclonedds#467]
## Bug report

**Required Info:**
- Operating System:
  - Ubuntu 20.04 Docker Container
- Installation type:
  - Binaries
- Version or commit hash:
  - 
- DDS implementation:
  - rmw_cyclonedds_cpp
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
I've cloned and built the Autoware stack on ROS galactic and the stack runs for the most part, except for some missing pointcloud messages that aren't being received from the simulator. The recommended rmw implementation for Autoware is cyclonedds and when I try to set the RMW_IMPLEMENTATION to rmw_cyclonedds_cpp and pass it the configuration file provided in Autoware's documentation, I get an unknown element error for two of the elements in the config xml file. The following is the content of the xml file.

`<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
<Domain Id="any">
        <General>
            <Interfaces>
                <NetworkInterface autodetermine="true" priority="default" multicast="default" />
            </Interfaces>
            <AllowMulticast>default</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
        </General>
        <Internal>
            <SocketReceiveBufferSize min="10MB"/>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
    </Domain>
</CycloneDDS>`

#### Expected behavior
The nodes spin up as usual with the new cyclonedds configuration settings.

#### Actual behavior
The cyclonedds implementation is unable to parse the config xml file. Particularly the "Interfaces" and "SocketReceiveBufferSize" tags.

**Comment by clalancette** [comment]
This seems like a problem with the Autoware documentation.  Please open up a bug with Autoware.

(I'll also note that Galactic is End-of-Life now)
