### ISSUE TITLE
Galactic CycloneDDS 0.8 check_whc Assertion failed crash

### ISSUE THREAD

**Issue by NamanMM** [ros2/rmw_cyclonedds#475]
Hello everyone,

I have been getting the following failure (In the callback function of the node) resulting in the crash. It is sporadic and slightly tricky to reproduce but here is the error message:

/tmp/binarydeb/ros-galactic-cyclonedds-0.8.0/src/core/ddsc/src/dds_whc.c:284: check_whc: Assertion `whc->maxseq_node->next_seq == NULL' failed.

Any pointers or suggestion will be appreciated. 
Thank you in advance.

**Comment by clalancette** [comment]
Unfortunately Galactic is End-of-Life.  Please try to reproduce the problem with one of the supported distributions (Humble, Iron, or Rolling), and re-open if necessary.

**Comment by eboasson** [comment]
Galactic is end of life, but @NamanMM was kind enough to also create https://github.com/eclipse-cyclonedds/cyclonedds/issues/1876: it definitely is a Cyclone DDS issue, and who knows if it still exists. I’ll follow up there as well
