### ISSUE TITLE
usage of getenv results in warning on Windows

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rmw_cyclonedds#71]
See https://ci.ros2.org/view/packaging/job/packaging_windows/1566/warningsResult/

Introduced in #60.

Use the function from [rcutils](https://github.com/ros2/rcutils/blob/fe215b4a3db580358f09bda6269e1356165fa920/include/rcutils/get_env.h#L62) instead.

**Comment by nuclearsandwich** [comment]
Resolved by https://github.com/ros2/rmw_cyclonedds/pull/73
