### ISSUE TITLE
failing ros1_bridge tests

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rmw_cyclonedds#72]
See https://ci.ros2.org/view/packaging/job/packaging_linux/1675/testReport/ which is trying to run a ROS 1 talker, the [ros1_bridge](https://github.com/ros2/ros1_bridge) `dynamic_bridge`, and ROS 2 listener.

The problem for the failure seems pretty similar to ros2/rmw_fastrtps#265. The logging messages are published as a C message containing a string. The actual message exchanged between the talker and listener is a C++ message (based on the same `.msg`). I assume the first advertised topic will "lock in" the C message type and then falsely try to use the same typesupport to read the C++ message which fails with `realloc(): invalid pointer`.

**Comment by eboasson** [comment]
> I assume the first advertised topic will "lock in" the C message type and then falsely try to use the same typesupport to read the C++ message which fails with realloc(): invalid pointer.

The type support is indeed cached in the topic. This is something that needs to be changed in Cyclone for mixed-language use and not very difficult (and I'm all in favour of it).

**Comment by dirk-thomas** [comment]
Resolved by #96.

Linux packaging build: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=295)](https://ci.ros2.org/job/ci_packaging_linux/295/) (one unrelated CMake warning).
