### ISSUE TITLE
Multiple cyclonedds failures on Windows

### ISSUE THREAD

**Issue by ivanpauno** [ros2/rmw_cyclonedds#83]
Unfortunately, [nightly_win_extra_rmw_rel](https://ci.ros2.org/view/nightly/job/nightly_win_extra_rmw_rel/) job have failed or been aborted 7 times in a row, but the last completed run showed many test failures:

https://ci.ros2.org/view/nightly/job/nightly_win_extra_rmw_rel/543/#showFailuresLink

Some of the aborted runs were also showing similar failures.

**Comment by ivanpauno** [comment]
Transferred to `rmw_cyclone_dds` from visibility.

**Comment by dirk-thomas** [comment]
A test build with CycloneDDS on Windows shows a few more than usual test failures: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8800)](https://ci.ros2.org/job/ci_windows/8798/).

@eboasson FYI.

**Comment by ivanpauno** [comment]
Re-triggering the same job, the situation seems to have improved in the nightlies:
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9494)](https://ci.ros2.org/job/ci_windows/9494/).

**Comment by ivanpauno** [comment]
Closing, as the remaining failures doesn't seem to be specific of `Windows`.
